# Spark name
spark.master                            spark://spark-master:7077
spark.app.name                          MySparkApp

# Resource allocation
spark.executor.instances                3
spark.executor.memory                   2g
spark.executor.cores                    2
spark.driver.memory                     1g
spark.driver.cores                      2

# Performance tuning
spark.sql.shuffle.partitions            50
spark.sql.adaptive.enabled              true
spark.serializer                        org.apache.spark.serializer.KryoSerializer

# Log settings
spark.eventLog.enabled                  true
spark.eventLog.dir                      /opt/spark/spark-events
spark.history.fs.logDirectory           /opt/spark/spark-events

# Memory management
spark.memory.fraction                   0.4
spark.memory.storageFraction            0.3

# Shuffle settings
spark.shuffle.compress                  true
spark.io.compression.codec              snappy
